Add atom object name on the  `cmd.get_model()` returned model
schrodinger/pymol-open-source pull request #380
Opened 2024-08-06 21:25 UTC by pslacerda

Now `cmd.get_model()` returns an atom model with the object name on it. I didn't want to use the `object` variable because it is a built-in, however I thought that any other name would be misleading.

2024-08-06 21:52 UTC, JarrettSJohnson commented
Aside from the compilation errors, I'm wondering if this is the right approach. Wouldn't each atom's object name be duplicated (wasted space)? Would it make sense to have the name be stored per-object/model rather than per-atom?

2024-08-06 22:16 UTC, pslacerda commented
I had this doubt and thought that `resn` is duplicate all over atoms, specially for polymers and decided to replicate.

And I'm not sure if the same happens when the string is built from the C API, but Python's strings of the same value share the same memory space.

2024-08-06 22:18 UTC, pslacerda commented
I decided to return the object name on the atom model because it's convenient. It would be even more if it worked on `iterate`.

2024-08-07 03:03 UTC, JarrettSJohnson requested changes
LGTM, just mostly one suggestion regarding variable usage.

I take back my comment regarding having `model` on the `model` level since I was under the impression these were exported as separate models, but this probably makes the most sense to align w/ iterate.

2024-08-07 03:03 UTC, JarrettSJohnson commented on layer3/MoleculeExporter.cpp
> +        m_iter.getAtomInfo(), m_last_obj, m_coord, getRefPtr(),
I think `m_iter.obj` is meant to be used instead. `m_last_obj` I think is mostly just used to distinguish object separation from adjacent atoms being iterated.

2024-08-07 03:03 UTC, JarrettSJohnson commented on layer2/CoordSet.h
> +                                   const float *v, const float *ref, int index, const double *matrix);
Optional: `clang-format` used for formatting C++ files for changed lines.

In the future, there will be enforced format checks during CI runs, but I won't sweat over it for now.

2024-08-07 14:35 UTC, JarrettSJohnson approved these changes

2024-08-07 14:35 UTC, merged

2024-08-07 18:41 UTC, JarrettSJohnson commented
Thanks for the PR!