refactoring shortcut.py script
schrodinger/pymol-open-source pull request #391
Opened 2024-08-17 12:45 UTC by ye11owSub

2024-09-03 18:10 UTC, ye11owSub commented
@JarrettSJohnson Could you please take a look at this PR?

2024-09-04 00:54 UTC, JarrettSJohnson commented
Yup, I plan to review after 3.1 is out later this month.

2024-09-04 10:38 UTC, ye11owSub commented
> Yup, I plan to review after 3.1 is out later this month.

copy that, thank you

2025-01-05 05:28 UTC, JarrettSJohnson requested changes

2025-01-05 05:28 UTC, JarrettSJohnson commented on modules/pymol/shortcut.py
> +    def make_abbreviation(self, s: str, groups_length: int) -> str:
Is this part of the public API (I didn't see any tests or usages in the codebase that uses this method explicitly)? If it's just meant to be internally used by `Shortcut`, can you add a leading underscore. I appreciate the examples here; also can you add a brief sentence or two on what this is achieving?

2025-01-05 05:28 UTC, JarrettSJohnson commented on modules/pymol/shortcut.py
> +    def rebuild(self, keywords: Optional[Iterable] = None) -> None:
Can you add a docstring for this and the other methods as well?

2025-01-05 05:28 UTC, JarrettSJohnson commented on tests/pymol/test_shortcut.py
Can this test be kept with the other tests? `test` and `testing` is already confusing as it is, and `tests` would just add to the confusion.

2025-01-05 18:04 UTC, ye11owSub commented on modules/pymol/shortcut.py
> +    def make_abbreviation(self, s: str, groups_length: int) -> str:
done

2025-01-05 18:04 UTC, ye11owSub commented on modules/pymol/completing.py
> +        v = cmd.setting.setting_sc.interpret(keyword[2:])
done

2025-01-05 18:05 UTC, ye11owSub commented on modules/pymol/shortcut.py
> +    def rebuild(self, keywords: Optional[Iterable] = None) -> None:
done

2025-01-05 18:18 UTC, ye11owSub commented on tests/pymol/test_shortcut.py
The tests in the `tests` folder are a duplicate of the tests in the `test` folder, except that the more modern and widely used pytests library is used instead. I would like to gradually replace the old tests without deleting them. What do you think about it ?

2025-01-05 18:24 UTC, ye11owSub commented on tests/pymol/test_shortcut.py
it will be a long process, but in the end it should improve readability

2025-01-05 18:28 UTC, JarrettSJohnson commented on tests/pymol/test_shortcut.py
We have some tests here that are `pytest` already (see https://github.com/schrodinger/pymol-open-source/blob/master/testing/tests/api/test_editing.py) for example. Some tests have been already converted to `pytest` from `unittest` in our other repo; I just haven't got around to bringing them over here.

2025-01-05 19:58 UTC, ye11owSub commented on tests/pymol/test_shortcut.py
understood. I just replaced the old tests with new ones.

2025-01-06 23:36 UTC, JarrettSJohnson reviewed
Looks good. Just this final thing and I'll merge it in later this week.

2025-01-06 23:36 UTC, JarrettSJohnson commented on modules/pymol/shortcut.py
> +    def optimize_symbols(self, keyword: str) -> None:
Same for this one; probably just for internal usage.

2025-01-07 14:07 UTC, ye11owSub commented on modules/pymol/shortcut.py
> +    def optimize_symbols(self, keyword: str) -> None:
done

2025-01-25 04:34 UTC, JarrettSJohnson approved these changes

2025-01-25 04:34 UTC, merged

2025-01-25 04:37 UTC, JarrettSJohnson commented
Thanks for your patience. Looks good.